export const Blog_Categories = [
  "All",
  "Technology",
  "Programming",
  "Artificial Intelligence",
  "Web Development",
  "App Development",
  "Cybersecurity",
  "Data Science",
  "DevOps",
  "Animation",
  "News",
  "Business",
  "Finance",
  "Education",
  "Career",
  "Lifestyle",
  "Health & Fitness",
  "Travel",
  "Food",
  "Gaming",
  "Sports",
  "Entertainment",
  "Books",
  "Personal",
  "Other",
] as const;